[workspace]

members = ["server", "client", "secure"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.test]
# Enable optimizations for tests
opt-level = 3
